apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: <docker_image>
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: <settings_module>.settings
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: <django-persistent-storage>
          mountPath: /app/data
      volumes:
      - name: <django-persistent-storage>
        persistentVolumeClaim:
          claimName: <django-pvc>
