version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.2
    volumes:
      - ./logstash/config:/usr/share/logstash/pipeline
    environment:
      - xpack.monitoring.enabled=false
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
volumes:
  esdata:
    driver: local
