# Generated by Django 2.1.2 on 2018-10-15 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=255, null=True, verbose_name='MSISDN (e.g 254708374149)')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='FirstName')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='MiddleName')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='LastName')),
                ('trans_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='TransTime (e.g 20181009075311)')),
                ('trans_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='TransID (e.g MJ951H6YF7)')),
                ('trans_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='TransAmount (e.g 100.00)')),
                ('org_account_balance', models.CharField(blank=True, max_length=255, null=True, verbose_name='OrgAccountBalance (e.g 518663.00)')),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='InvoiceNumber')),
                ('bill_ref_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='BillRefNumber e.g(account name - testapi)')),
                ('third_party_transid', models.CharField(blank=True, max_length=255, null=True, verbose_name='ThirdPartyTransID')),
                ('business_short_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='BusinessShortCode (e.g 600520)')),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='TransactionType (e.g Pay Bill)')),
                ('status', models.IntegerField(default=0, verbose_name='status( [0 - not picked], [1 - picked], [2 -inserted to db] )')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date of update')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date of create')),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payment',
            },
        ),
    ]
